// src/components/seeds.js
export const seeds = [
  {
    seed_id: 1,
    name: "NERICA L-19",
    variety: "L-19",
    crop_type: "rice",
    maturity_days: 120,
    quality_grade: "A",
    certification_status: "certified",
    region: "Eastern Province",
    distributor: "AgroFarm",
    stock_quantity: 100,
    unit: "kg",
    price_per_unit: 5000,
    status: "available",
  },
  {
    seed_id: 2,
    name: "Maize Sweet",
    variety: "Sweet Corn",
    crop_type: "maize",
    maturity_days: 90,
    quality_grade: "B",
    certification_status: "approved",
    region: "Northern Province",
    distributor: "SeedCo",
    stock_quantity: 50,
    unit: "kg",
    price_per_unit: 3000,
    status: "low_stock",
  },
  {
    seed_id: 3,
    name: 'Cassava Super',
    variety: 'Fast-growing',
    crop_type: 'cassava',
    region: 'Southern Province',
    distributor: 'Harvest Ltd',
    stock_quantity: 0,
    unit: 'kg',
    price_per_unit: 4000,
    status: 'out_of_stock',
    certification_status: 'pending',
  },
  {
    seed_id: 4,
    name: 'Groundnut Jumbo',
    variety: 'Peanut',
    crop_type: 'groundnut',
    region: 'Western Area',
    distributor: 'AgroPlus',
    stock_quantity: 75,
    unit: 'bags',
    price_per_unit: 4500,
    status: 'available',
    certification_status: 'certified',
  },
  {
    seed_id: 5,
    name: 'Sorghum Red',
    variety: 'Drought-resistant',
    crop_type: 'sorghum',
    region: 'North West Province',
    distributor: 'SierraSeeds',
    stock_quantity: 30,
    unit: 'kg',
    price_per_unit: 3500,
    status: 'low_stock',
    certification_status: 'approved',
  },
];